### ISSUE TITLE
Spark 2.3

### ISSUE THREAD

**Issue by acharnoff** [twosigma/flint#28]
Are there any plans to update Flint to run on Spark 2.3? I would love to be able to use pandas_udf's on my Time Series DataFrames.

Thanks!

**Comment by kenahoo** [comment]
Coincidentally I came here to ask whether 2.3 is supported - is the README just out of date and it means 2.2 is the *minimum* version, or is 2.3 explicitly not working?

**Comment by icexelloss** [comment]
Hi,

It does work with 2.3. The readme needs update.
