### ISSUE TITLE
Compilation error 

### ISSUE THREAD

**Issue by rcastbergw** [twosigma/flint#4]
Running sbt assembly compilation fails due to missing  slf, it was resolved by adding :

Adding, 
"org.slf4j" % "slf4j-simple" % "1.6.4"
to libraryDependencies allowed it to compile.

Though i had no problems when i ran make dist.

**Comment by icexelloss** [comment]
Hi,

I cleared my ivy cache but was not able to reproduce the issue . I will leave this open and see if others have this issue as well.

**Comment by mforsyth** [comment]
Could not reproduce.  I was trying on a completely fresh workstation (I had never even used sbt before).
