### ISSUE TITLE
"Rankers" Import error

### ISSUE THREAD

**Issue by gbaettig** [twosigma/flint#41]
I can successfully open the PySpark shell with the command provided on your python/README.md file

`pyspark --master=local --jars /path/to/assembly/flint-assembly-0.6.0-SNAPSHOT.jar --py-files /path/to/assembly/flint-assembly-0.2.0-SNAPSHOT.jar`

However, when I try to import the ts.flint module with the command

`import ts.flint`

I always get the error 

` cannot import name 'rankers' `

Am I missing something? The file python/ts/flint/dataframe.py contains the statement 

` from . import rankers `

but I cannot find any such file in the repository. 

Any help would be appreciated.

**Comment by icexelloss** [comment]
Hi,

I think you need to pass `--py-files /path/to/assembly/flint-assembly-0.6.0-SNAPSHOT.jar`

rankers has been removed in a recent commit, you can try pulling from the latest?

**Comment by gbaettig** [comment]
Thanks for your reply, I will pull the latest version and let you know if the error disappeared.

**Comment by gbaettig** [comment]
The error seems to have disappeared. Pulling the latest version worked. Thank you.
