### ISSUE TITLE
Design question: Can I use LeftSubtractableSummarizer for snapshot reconstruction

### ISSUE THREAD

**Issue by soloman817** [twosigma/flint#43]
Just dive into the source code of flint, looks very good. Now I have a new requirement and I'm trying to create a custom summarizer. It would be better if you guys can give me some feedback on the usage.

So, say we have a time series of events, some events are snapshot, but most events are delta, which will be applied to previous snapshot. The snapshot might be very large, say, the whole order book levels. This is why we cannot store the snapshot (the actual state) into the time series data.

So I started a simplified version. Say the snapshot is just a Long, and the delta is also Long. Like this:

```
+----+--------+-----+
|time|snapshot|delta|
+----+--------+-----+
|1000|    null|    1|
|1010|    null|    1|
|1050|       8| null|
|1100|    null|    1|
|1200|    null|    1|
|1250|    null|    1|
|1350|      11| null|
|1550|    null|    1|
+----+--------+-----+
```

From there, I want to create a summarizer that can reconstruct the snapshots, then grab some information of the snapshot at each event. Say, I want to generate the final data frame like:

```
+----+--------+-----+----------------------+
|time|snapshot|delta|reconstructed_snapshot|
+----+--------+-----+----------------------+
|1000|    null|    1|                  null|
|1010|    null|    1|                  null|
|1050|       8| null|                     8|
|1100|    null|    1|                     9|
|1200|    null|    1|                    10|
|1250|    null|    1|                    11|
|1350|      11| null|                    11|
|1550|    null|    1|                    12|
+----+--------+-----+----------------------+
```

The first two rows are still null because there is no start snapshot. But after the first snapshot, we should be able to reconstruct the snapshot for each event.

Now, I want to extend a custom summarizer, and I saw most of the summarizers are extended from `LeftSubtractableSummarizer`. I also found there is a property test for `LeftSubtractableProperty`, there it wrote: "Check if (a + b) + c - a = b + c"

In logic, the snapshot reconstruction is left subtractable. But in reality, for a window, we must know the snapshot of the first event in that window, otherwise it cannot construct. So for this reason, I start to define my summarizer as: `case class Experiment1Summarizer() extends LeftSubtractableSummarizer[Option[Long], Option[Long], Option[Long]]`

The three types, T, U and V are all `Option[Long]` because of this reason. So it will not pass the `LeftSubtractableProperty` obviously. For example:

```
a = |1050|       8| null|
b = |1100|    null|    1|
c = |1200|    null|    1|
a + b + c = Some(10)  a is snapshot
a + b + c - a = Some(10), because remove an old event will not effect the state
but, b + c = None, because there is no start snapshot.
```

So, does this make sense to use `LeftSubtractableSummarizer` to implement?

Regards,
Xiang.

**Comment by soloman817** [comment]
I quickly coded one implementation:

```
  case class Event(kind: String, value: Long)

  case class Experiment1Summarizer() extends LeftSubtractableSummarizer[Event, Option[Long], Option[Long]] {
    override def subtract(u: Option[Long], v: Event): Option[Long] = u

    /**
      * @return the initial state of this summarizer.
      */
    override def zero(): Option[Long] = None

    /**
      * Update a state with a given value. The original u can be changed after [[add()]].
      *
      * @param u The prior state.
      * @param t A value expected to use for updating the prior state.
      * @return updated state
      */
    override def add(u: Option[Long], t: Event): Option[Long] = (u, t) match {
      case (None, Event("snapshot", value)) => Some(value)
      case (None, Event("delta", value)) => None
      case (Some(state), Event("snapshot", value)) => if (state == value) Some(state) else throw new RuntimeException("snapshot doesn't match")
      case (Some(state), Event("delta", value)) => Some(state + value)
      case _ => throw new RuntimeException("bug")
    }

    /**
      * Merge two summarizer states. The original u1 and u2 can be changed after [[merge()]]
      *
      * For two sequences (a[1], a[2], ..., a[n]), (a'[1], a'[2], ..., a'[m]), and two states u1 and
      * u1 where
      * u1 = 0 + a[1] + ... + a[n]
      * u2 = 0 + a'[1] + ... + a'[m]
      *
      * It must satisfy the following condition.
      * u1 + u2 = 0 + a[1] + ... + a[n] + a'[1] + ... + a'[m]
      *
      * @param u1 A state expected to merge as the left hand side of merge operation.
      * @param u2 A state expected to merge as the right hand side of merge operation.
      * @return the merged state
      */
    override def merge(u1: Option[Long], u2: Option[Long]): Option[Long] = (u1, u2) match {
      case (None, None) => None
      case (None, Some(uu2)) => Some(uu2)
      case (Some(uu1), None) => None  // I assume time of u1 will be smaller than u2, is this true?
      case (Some(uu1), Some(uu2)) => Some(uu2)  // I assume the time of u1 and u2 are consective, is this true?
    }

    /**
      * Renders a state into the output type. The original u should NOT change after [[render()]]
      *
      * @param u state expected to render
      * @return a rendered value with desired type.
      */
    override def render(u: Option[Long]): Option[Long] = u
  }
```

This only works if:
  1. for merge, the time of u1 and u2 should be consecutive and times(u1) < times(u2), don't know if this is true in your implementation

**Comment by icexelloss** [comment]
Hi, left subtract is used when you have a rolling window and you want to aggregate for each rolling window. Snapshot reconstruction feels like a scan operation with a state for the current snapshot. I am not sure left subtract is useful here (but I haven't thought too hard either).
