### ISSUE TITLE
Example of sqlContext in Weather.ipynb and Flint Example.ipynb

### ISSUE THREAD

**Issue by yezhengli-Mr9** [twosigma/flint#73]
Example of SQLContext in Weather.ipynb and Flint Example.ipynb?

I get ```TypeError: 'JavaPackage' object is not callable``` by trying some SQLContext (although I believe this is my configuration issue).

Thanks!

**Comment by ashishk96** [comment]
I am having the same issue. Could you share what did you do to fix it?

**Comment by pohutukawa** [comment]
@yezhengli-Mr9 @ashishk96: I've been fighting the same (and further problems).

Have a look at #77 on how to get things to (mostly) work well. Noteworthy are the two JARs you need to grab and place in the right locations as well as the code snippet on how to obtain access to the the `spark` object at the head of the file.
